### ISSUE TITLE
ERROR:cannot launch node of type [ssl_slam/ssl_slam_laser_processing_node]

### ISSUE THREAD

**Issue by zsm666** [wh200720041/ssl_slam#31]
ERROR: cannot launch node of type [ssl_slam/ssl_slam_laser_processing_node]: Cannot locate node of type [ssl_slam_laser_processing_node] in package [ssl_slam]. Make sure file exists in package path and permission is set to executable (chmod +x)
ERROR: cannot launch node of type [ssl_slam/ssl_slam_odom_estimation_node]: Cannot locate node of type [ssl_slam_odom_estimation_node] in package [ssl_slam]. Make sure file exists in package path and permission is set to executable (chmod +x)
ERROR: cannot launch node of type [ssl_slam/ssl_slam_laser_mapping_node]: Cannot locate node of type [ssl_slam_laser_mapping_node] in package [ssl_slam]. Make sure file exists in package path and permission is set to executable (chmod +x)

**Comment by zsm666** [comment]
i don't know why?please help?

**Comment by LEEJUNHO95** [comment]
> i don't know why?please help?

do you resolve this issue????

**Comment by LEEJUNHO95** [comment]
I had the same problem as you, but I solved it this way.

solution 
1. When installing "ceres_solve", did you install the correct version? 2.1 version is stable, but 2.2 version should match the cmake version, so I recommend 2.1 is recommended.
2. When proceeding with the "ceres_solve" tutorial, did the tutorial proceed perfectly? In my case, I ran "make install" because "make install" was written in the tutorial, but it didn't work. I ignored it and proceeded. As a result, "sudo make install" was required. "
3. The "ceres_solve" package must exit the work_station. In my case, I put it in the home folder, not the work_station folder. In this way, I had the same problem as you, but I solved it.

**Comment by zsm666** [comment]
> I had the same problem as you, but I solved it this way.
> 
> solution
> 
> 1. When installing "ceres_solve", did you install the correct version? 2.1 version is stable, but 2.2 version should match the cmake version, so I recommend 2.1 is recommended.
> 2. When proceeding with the "ceres_solve" tutorial, did the tutorial proceed perfectly? In my case, I ran "make install" because "make install" was written in the tutorial, but it didn't work. I ignored it and proceeded. As a result, "sudo make install" was satisfied. "
> 3. The "ceres_solve" package must exit the work_station. In my case, I put it in the home folder, not the work_station folder. In this way, I had the same problem as you, but I solved it.

I solved it by a similar way,Thanks bro
